[fpga.pynq]
part       = "xc7z020clg400-1"
board_part = "tul.com.tw:pynq-z2:part0:1.0"
board_repo = "/home/laperex/Programming/Vivado/vivado-boards/new/board_files"

[[ip]]
name = "ip_rgb_to_hsv"
vendor = "laperex.org"
library = "custom_axi_ip"
version = "1.0"

create-wrapper = true

rtl = [
	"srcs/rtl/axi_types.sv",
	"srcs/rtl/axi_lite_slave.sv",

	"srcs/rtl/cv_types.sv",
	"srcs/rtl/cv_rgb_to_hsv.sv",

	"srcs/rtl/ip_rgb_to_hsv.sv"
]

[[ip]]
name = "ip_inrange"
vendor = "laperex.org"
library = "custom_axi_ip"
version = "1.0"

create-wrapper = true

rtl = [
	"srcs/rtl/axi_types.sv",
	"srcs/rtl/axi_lite_slave.sv",

	"srcs/rtl/cv_types.sv",
	"srcs/rtl/cv_inrange.sv",

	"srcs/rtl/ip_inrange.sv"
]

[[bd]]
name = "bd_image_processing"

[[synthesis]]
bd = "bd_image_processing"