[vivado]
path = "/opt/Xilinx/Vivado/2024.1"

max_threads = 20
mode = "batch"

[vitis]
path = "/opt/Xilinx/Vitis/2024.1"

[fpga]
part       = "xc7z020clg400-1"
board_part = "tul.com.tw:pynq-z2:part0:1.0"
board_repo = "/home/laperex/Programming/Vivado/vivado-boards/new/board_files"

[build]
dir = "build"
ip_repo = "build/ip"
bd_dir = "build/bd"

wrapper_dir = "srcs/rtl/wrapper"

[sources]
rtl = [
	"srcs/rtl/**/*.sv",
	"srcs/rtl/**/*.v",
]

sim = [
	"srcs/rtl/**/*.sv",
	"srcs/sim/ip_systolic_tb.sv",
]

[[ip]]
name = "ip_rgb_to_hsv"
vendor = "laperex.org"
library = "custom_axi_ip"
version = "1.0"
top = "ip_rgb_to_hsv_wrapper"

rtl = [
	"srcs/rtl/axi_types.sv",
	"srcs/rtl/axi_lite_slave.sv",
	"srcs/rtl/ip_rgb_to_hsv.sv",
	"srcs/rtl/ip_rgb_to_hsv_wrapper.sv",
]

[[ip]]
name = "ip_inrange"
vendor = "laperex.org"
library = "custom_axi_ip"
version = "1.0"
top = "ip_inrange_wrapper"

rtl = [
	"srcs/rtl/axi_types.sv",
	"srcs/rtl/axi_lite_slave.sv",
	"srcs/rtl/ip_inrange.sv",
	"srcs/rtl/ip_inrange_wrapper.sv",
]

[[bd]]
name = "bd_systolic_test"
version = "1.0"

hooks = "scripts/bd/bd_systolic_test_1.0.tcl"

[[synthesis]]
top = "bd_systolic_test_wrapper"
hooks = "scripts/synth/bd_systolic_test_wrapper.tcl"

fpga = "pynq_z2"